### ISSUE TITLE
Need Chinese Localization

### ISSUE THREAD

**Issue by TokamakYuri** [dfint/installer#32]
There is no Chinese in dictionary. Is it because the new hook don't support chinese character or just not add to it yet?

**Comment by insolor** [comment]
In short - yes. We don't have any good news about support of Chinese

вс, 31 мар. 2024 г., 17:26 Tokamak Sullivan ***@***.***>:

**Comment by TokamakYuri** [comment]
So I guess it might because the chinese character's encoding is different to other Latin script?

**Comment by insolor** [comment]
@TokamakYuri, this is because DF itself supports only 256-character bitmap (pixel) fonts, each character 8x12 px. No unicode support, only single byte encodings.

This is not only latin script support but also Cyrillic, potentially Greek, Georgian, Armenian and other languages with "compact" alphabets. More or less, it is possible to support everything that can fit in 256 characters.

Sadly - no Chinese, Japanese, Korean and other languages with hieroglyphic scripts. Also no support for languages with right-to-left script.

To support hieroglyphs, it is necessary to heavily modify the way how the game draws symbols.

**Comment by TokamakYuri** [comment]
Oh, I see. Very appreciate your explanation.

**Comment by linonetwo** [comment]
Any chance to add unicode support, like add custom font to it?

Starbound is also using bitmap font, but its CJK support can be added by installing a font mod https://steamcommunity.com/sharedfiles/filedetails/?l=schinese&id=807695810

**Comment by linonetwo** [comment]
How does this work? Can https://github.com/trotsky1997/df-steam-hook 's work be reimplemented into df-steam-hook-rs?

**Comment by insolor** [comment]
> Any chance to add unicode support, like add custom font to it?
> 
> Starbound is also using bitmap font, but its CJK support can be added by installing a font mod [steamcommunity.com/sharedfiles/filedetails?l=schinese&id=807695810](https://steamcommunity.com/sharedfiles/filedetails/?l=schinese&id=807695810)

@linonetwo it's not possible without modifying of the code of the game.

> How does this work? Can [trotsky1997/df-steam-hook](https://github.com/trotsky1997/df-steam-hook) 's work be reimplemented into df-steam-hook-rs?

May be yes, may be no. It needs to be investigated by someone who is interested.

As for df-steam-hook forks for Chinese, as far as I remember, it was already broken since some DF version, before we switched to df-steam-hook-rs. So, I guess there are some other problems aside from reimplementing it in rust.
