### ISSUE TITLE
Crash when adding a new profession in Labor screen on DF 0.50.12 / 0.50.12a on Windows

### ISSUE THREAD

**Issue by Sahok1** [dfint/installer#39]
Problem relates to the **Russian/Russian (cp866)** localization on DF 0.50.12 / 0.50.12a on Windows 10

When you want to add a new profession Labor screen, the game simply closes without any errors. At the same time, I managed to create 2 additional professional ones - a "Огранщик" and "Инкрустатор". When adding more, it crashes.

At the same time, the number of possible additions without crash varies from 1 to 2 in different worlds and under different circumstances.

I have sometimes managed to create both 1 and 2 additional professions, but never more than two. I didn't notice any system in the crashes. It's just that sometimes it turns out to create a second additional profession, and sometimes not.
![12](https://github.com/dfint/installer/assets/42940187/a88cf472-7893-45f1-8731-c3a1e479b1e0)

When removing the hook and localization, the bug disappears and it becomes possible to create more than two additional professions
![13](https://github.com/dfint/installer/assets/42940187/fcd6486e-14bd-451e-9493-e74f44af731c)
![134](https://github.com/dfint/installer/assets/42940187/fa79a87e-22f8-4dd0-89af-db7be7e4afeb)

When I need to create new professions, I delete the localization through the installer, create professions, put the localization back and continue playing.

I am attaching a crash log, I hope it will tell you something

[crash_2024-03-31-18-47-15.txt](https://github.com/dfint/installer/files/14822275/crash_2024-03-31-18-47-15.txt)

**Comment by insolor** [comment]
Does it crash with "English" (empty) dictionary?

**Comment by Sahok1** [comment]
> Does it crash with "English" (empty) dictionary?

No. When Hook is installed and dictionary.csv empty, crash does not occur

**Comment by insolor** [comment]
@Sahok1 fixed. Please update the dictionary using installer.

**Comment by Sahok1** [comment]
> @Sahok1 fixed. Please update the dictionary using installer.

Yes, now everything works fine, great work!

If it's not difficult, tell me what was the problem, please? As I understood it, the problem was in the dictionary and I couldn't find the problem item at first glance

**Comment by insolor** [comment]
Translation of some strings may cause some problems, because they are used internally (i.e., they are not visible to the user, but some strings are used both internally and externally).
Excluding of such strings from translation fixes the issue.

So, I needed to pinpoint which string is problematic. To do it, I needed to split the dictionary in half, check on which half the crash still occurs, then split in half again, and so on, until I got exactly one string. This method is similar to a bisection or a binary search.

To do such splitting (bisection), we have [csv-bisect-gui](https://github.com/dfint/csv-bisect-gui) tool. 

This time it was "Details" string. So, I've excluded it on transifex and then rebuild dictionaries.
